---
- name: Drop home configs on this host
  hosts: all
  tasks:
    - name: "copy over home directory configs - {{ home_directory }}"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ home_directory }}"
        mode: "0600"
      with_items:
        - "{{ home_files }}"

    - name: "copy over .gitconfig"
      ansible.builtin.template:
        src: gitconfig.j2
        dest: "{{ home_directory }}/.gitconfig"
        mode: "0600"
