---
- name: Drop home configs on this host
  hosts: all
  tasks:
    - name: "create default home directories"
      ansible.builtin.file:
        path: "{{ home_directory }}/{{ item }}"
        state: directory
        mode: "0750"
      with_items:
        - "{{ default_directories }}"

    - name: "copy over home directory configs - {{ home_directory }}"
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0600"
      with_items:
        - "{{ home_files }}"

    - name: "copy over .gitconfig"
      ansible.builtin.template:
        src: gitconfig.j2
        dest: "{{ home_directory }}/.gitconfig"
        mode: "0600"

    - name: "create .ssh directory"
      ansible.builtin.file:
        path: "{{ home_directory }}/.ssh"
        state: directory
        mode: "0700"

    - name: "un-ecrypt and copy over ssh configs"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ home_directory }}/.ssh/{{ item.split('.')[1] }}"
        mode: "0600"
      with_items:
        - "{{ ssh_files }}"
