name: Ansible Test Run

on: [push, pull_request]

jobs:

  ansible-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      # replace "master" with any valid ref
      uses: ansible/ansible-lint-action@master
      with:
        # [required]
        # Paths to ansible files (i.e., playbooks, tasks, handlers etc..)
        # or valid Ansible directories according to the Ansible role
        # directory structure.
        # If you want to lint multiple ansible files, use the following syntax
        targets: |
          playbook.yml
          group_vars/
        # override-deps due to the following issue:
        # https://github.com/ansible/ansible-lint-action/issues/59
        override-deps: |
           rich>=9.5.1,<11.0.0

  ansible-test-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: playbook.yml
        # Optional, directory where playbooks live
        directory: ./
        # Optional, literal inventory file contents
        inventory: |
          [local]
          localhost ansible_connection=local
        # Optional, galaxy requirements filepath
        # requirements: galaxy-requirements.yml
        # Optional, additional flags to pass to ansible-playbook
        options: |
          --limit local
          --verbose